apiVersion: v2
name: prometheus-operator-crds
description: Prometheus Operator CRDs (no values - install before kube-prometheus-stack).
type: application
version: 1.0.1
appVersion: "v0.87.1"
dependencies:
  - name: prometheus-operator-crds
    version: "16.0.0"
    repository: "https://prometheus-community.github.io/helm-charts"
# comment hello from the first try 
