apiVersion: v2
name: thanos
description: Thanos query, store, compactor and query-frontend stack.
type: application
version: 1.0.1
appVersion: "17.3.1"
dependencies:
  - name: thanos
    version: "17.3.1"
    repository: "https://charts.bitnami.com/bitnami"
